<?php

/**
 * O-Level subjects list, ordered with most common subjects first.
 */
return [
    // Core / Most Common
    'English Language',
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Further Mathematics',
    'Agricultural Science',
    'Economics',
    'Government',
    'Literature in English',
    'Commerce',
    'Accounting/Financial Accounting',
    'Geography',
    'Civic Education',
    'Computer Studies/ICT',
    'Christian Religious Studies',
    'Islamic Religious Studies',
    'History',
    'French',
    'Arabic',
    'Hausa',
    'Igbo',
    'Yoruba',

    // Sciences
    'Health Education',
    'Physical Education',
    'Technical Drawing',
    'Basic Electronics',
    'Basic Electricity',
    'Auto Mechanics',
    'Metal Work',
    'Woodwork',
    'Building Construction',
    'Food and Nutrition',
    'Home Economics',
    'Clothing and Textiles',
    'Animal Husbandry',
    'Fisheries',
    'Dyeing and Bleaching',

    // Arts & Social Sciences
    'Visual Arts/Fine Arts',
    'Music',
    'Book Keeping',
    'Office Practice',
    'Typewriting',
    'Shorthand',
    'Store Keeping',
    'Insurance',
    'Salesmanship',
    'Clerical Office Duties',

    // Vocational / Technical
    'Data Processing',
    'Catering Craft Practice',
    'Garment Making',
    'Photography',
    'Printing Craft Practice',
    'Cosmetology',
    'Leather Goods Manufacturing',
    'Upholstery',
    'Painting and Decorating',
    'Plumbing and Pipe Fitting',
    'Machine Woodworking',
    'Carpentry and Joinery',
    'Furniture Making',
    'Welding and Fabrication',
    'Electrical Installation',
    'Radio/TV/Electronic Work',
    'Blocklaying/Bricklaying and Concreting',
    'Draughtsmanship',
    'GSM Phone Maintenance',
    'Tourism',

    // Languages
    'Edo',
    'Efik',
    'Ibibio',
    'Tiv',
    'Fulfulde',
    'Kanuri',
    'Nupe',
    'Ijaw',
    'Urhobo',
    'Itsekiri',
];
